### ISSUE TITLE
\LetLtxMacro broken by TeXlive 2023

### ISSUE THREAD

**Issue by jokuha** [ho-tex/letltxmacro#2]
It seems that \LetLtxMacro was broken by TeXlive 2023 :-o

For many years, I have been using the redefinition of autoref as specified at https://tex.stackexchange.com/questions/422029/autoref-with-optional-argument . This does not work anymore, and it seems that the issue is with the `\LetLtxMacro\autoreforig\autoref` not working right anymore.

**Comment by u-fischer** [comment]
please add a small but complete example in the issue, do not link only to external resources where one has to guess what you are actually doing.

**Comment by u-fischer** [comment]
`\LetLtxMacro` is not broken. `\autoref` has changed, it is now defined with `\NewDocumentCommand` and  the letltxmacro package doesn't handle such commands. Use  `\NewCommandCopy\autoreforig\autoref` to copy the command.
